version: '3'
services:

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - 8080:5000
    environment:
      BACKEND_URL: http://backend:5000/messages

  backend:
    build: ./backend
    image: backend
    container_name: backend
    environment:
      AWS_DEFAULT_REGION: us-east-1
      DYNAMODB_TABLE_NAME: messages
